[build]
  functions = "netlify/functions"

[dev]
  framework = "#static"

[[redirects]]
  from = "/tour/taotourmoi"
  to = "/ADMIN/add-tour.html"
  status = 200
  force = true

[[redirects]]
  from = "/tour/:slug"
  to = "/TOUR/detail.html?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/photo/:slug"
  to = "/.netlify/functions/photo?id=:slug"
  status = 301
  force = true
